sudo: required

services:
  - docker

script:
  - echo "No tests"

after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee -a /usr/bin/ecs-deploy
  - sudo chmod +x /usr/bin/ecs-deploy
  - eval $(aws ecr get-login --no-include-email --region eu-west-1)
  - docker build -t ok-lib-magento-1 .
  - docker tag ok-lib-magento-1:latest 914935490550.dkr.ecr.eu-west-1.amazonaws.com/ok-lib-magento-1:latest
  - docker push 914935490550.dkr.ecr.eu-west-1.amazonaws.com/ok-lib-magento-1:latest
  - ecs-deploy -c oklibmagento1 -n Magento -i ok-lib-magento-1:latest